-- create a new database db_sql_tutorial
Drop database if exists db_sql_tutorial;
CREATE DATABASE DB_SQL_TUTORIAL;
USE DB_SQL_TUTORIAL;

-- CREATE TABLE CUSTOMERS
DROP TABLE IF EXISTS DB_SQL_TUTORIAL.CUSTOMERS;
CREATE TABLE DB_SQL_TUTORIAL.CUSTOMERS (
    customer_id INT(10) NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NULL,
    score INT(32) NULL,
    PRIMARY KEY (customer_id)
);	
    
    -- Insert customers data
    insert into DB_SQL_TUTORIAL.customers VALUES (1, 'Maria', 'Cramer', 'Germany', 350);
    insert into DB_SQL_TUTORIAL.customers VALUES (2, 'John', 'Steel', 'USA', 900);
    insert into DB_SQL_TUTORIAL.customers VALUES (3, 'Georg', 'Pipps', 'UK', 750);
    insert into DB_SQL_TUTORIAL.customers VALUES (4, "Martins", "Muller", "Germany", 500);
    insert into DB_SQL_TUTORIAL.customers VALUES (5, "Peter", "Franken", "USA", NULL);
    
    -- create table orders
    DROP table IF EXISTS DB_SQL_TUTORIAL.ORDERS;
CREATE TABLE DB_SQL_TUTORIAL.ORDERS (
    ORDER_ID INT(10) NOT NULL AUTO_INCREMENT,
    CUSTOMER_ID INT(10) NOT NULL,
    ORDER_DATE DATE NULL,
    QUANTITY INT(32) NULL,
    PRIMARY KEY (ORDER_ID)
);
    
    -- INSERT VALUES INTO ORDERS TABLE
    INSERT INTO DB_SQL_TUTORIAL.ORDERS VALUES (1001, 1, "2021-01-11", 250);
    INSERT INTO DB_SQL_TUTORIAL.ORDERS VALUES (1002, 2, "2021-04-05",1150);
    INSERT INTO DB_SQL_TUTORIAL.ORDERS VALUES (1003, 3, "2021-06-18",500);
    INSERT INTO DB_SQL_TUTORIAL.ORDERS VALUES (1004, 6, "2021-08-31", 750);
    
    -- CREATE TABLE EMPLOYEES
    DROP TABLE IF EXISTS DB_SQL_TUTORIAL.EMPLOYEES;
CREATE TABLE DB_SQL_TUTORIAL.EMPLOYEES (
    EMP_ID INT(10) NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMP_COUNTRY VARCHAR(50) NULL,
    SALARY INT(32) NULL,
    PRIMARY KEY (EMP_ID)
);
    
    
-- INSERT THE DATA FOR EMPLOYEE TABLE
	INSERT INTO DB_SQL_TUTORIAL.EMPLOYEES VALUES (1, "JOHN", "STEEL", "USA", 55000);
    INSERT INTO DB_SQL_TUTORIAL.EMPLOYEES VALUES (2, "ANN", "LABRUNE", "FRANCE", 75000);
    INSERT INTO DB_SQL_TUTORIAL.EMPLOYEES VALUES (3, "MARIE", "BETRAND", "BRAZIL", 75000);
    INSERT INTO DB_SQL_TUTORIAL.EMPLOYEES VALUES (4, "GEORG", "AFONSO", "UK", 75000);
	INSERT INTO DB_SQL_TUTORIAL.EMPLOYEES VALUES (5, "MARIE", "STEEL", "UK", 75000);	
    
    
    
    